config/routes.rb
Rails.application.routes.draw do
  resources :messages
  root to: redirect("/#{I18n.default_locale}")

  scope "/:locale" do
    root 'homepage#index'
    devise_for :users
    resources :listings
    resources :categories
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
    belongs_to :user
    has_one :category
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :description, :price)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="field form-group">
      <%= form.label :title %> <br />
      <%= form.text_field :title %>
    </div>
    <div class="field form-group">
      <%= form.label :Category %> <br />
      <%= collection_select(:invoice, :category_id, Category.all, :id, :name) %> 
    </div>

    <div class="field form-group">
      <%= form.label :form_description %> <br />
      <%= form.text_field :description %>
    </div>

    <div class="field form-group">
      <%= form.label :price %> <br />
      <%= form.number_field :price %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </form>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<div class="container">
  <% @listings.each do |listing| %>
  <div style="border:solid 1px; padding: 2%;"> 
    <h3><% listing.title %></h3>
    <div class="d-flex justify-content-start align-items-center" >
   <%-#   <a><% listing.timestamps </a>#-%>
      <span class="badge badge-secondary"><% listing.title %></span>
    </div>
    <div class="row">
      <div class="col-2">
      <img src="/assets/images/background.jpg">
      </div>
      <div class="col">
        <a class="text-justify"><% listing.description %></a>                 
        <div class="d-flex justify-content-around align-items-center w-100" >
          <a><% listing.price %></a>
          <button class="btn btn-warning my-2 my-sm-0" type="button" data-toggle="modal" data-target="#exampleModal"><%= t :btn_contact_listing %></button>   
        </div>
      </div> 
    </div>
    </div>
  <% end %>
  <br>

<%= link_to 'New Listing', new_listing_path %>
</div>



  <%-#= do listing.title %>
  <!-- MODAL -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
	aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel"><%= t :btn_contact_listing %></h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form>
          <div class="form-group">
            <label><%= t :your_message %></label>
            <textarea class="form-control" id="exampleFormControlTextarea" rows="6"></textarea>
          </div>
        </form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t :send %></button>
			</div>
		</div>
	</div>
</div>

app/views/listings/new.html.erb
<div class="container">
    <div class="row">
        <div class="col">
        </div>
        <div class="col">
            <h1><%= t :new_listing %></h1>
            <form>
                <%= render 'form', listing: @listing %>

                <%= link_to 'Back', listings_path %>
            </form>
            
        </div>
        <div class="col">
        </div>
    </div>
</div>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>